# Generated by Django 5.0.1 on 2024-01-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_data_poster_alter_movie_data_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='poster',
            field=models.ImageField(blank=True, default='Unavailable', upload_to='images/'),
        ),
    ]
