# Generated by Django 5.0.1 on 2024-01-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_data_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie_data',
            options={'ordering': ('title',)},
        ),
    ]
