# Generated by Django 5.0.1 on 2024-02-05 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_censor_info_movie_data_censor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='censor_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='movies.censor_info'),
        ),
    ]
