# Generated by Django 5.0.1 on 2024-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_movie_data_directed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='movie_data',
            name='actor',
            field=models.ManyToManyField(related_name='acted_movies', to='movies.actors'),
        ),
    ]
