# Generated by Django 5.0.1 on 2024-02-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_actors_alter_director_name_movie_data_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='censor_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='movies.censor_info'),
        ),
    ]
