# Generated by Django 5.0.1 on 2024-02-07 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_movie_data_censor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='actor',
            field=models.ManyToManyField(blank=True, related_name='acted_movies', to='movies.actors'),
        ),
        migrations.AlterField(
            model_name='movie_data',
            name='directed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_by', to='movies.director'),
        ),
    ]
